{
  tokens=[
    OP_EQ="="
        OP_IS="::="
        OP_OR="|"
        OP_OPT="?"
        OP_ONEMORE="+"
        OP_ZEROMORE="*"
        OP_AND="&"
        OP_NOT="!"
        SEMICOLON=";"
        LEFT_BRACE="{"
        RIGHT_BRACE="}"
        LEFT_BRACKET="["
        RIGHT_BRACKET="]"
        LEFT_PAREN="("
        RIGHT_PAREN=")"
        EXTERNAL_START="<<"
        EXTERNAL_END=">>"

        space='regexp:\s+'
        id="regexp:\w+"
        string="regexp:('([^'\\]|\\.)*'|\"([^\"\\]|\\\"|\\\'|\\)*\")"
        notEmptyString="regexp:('([^'\\]|\\.)*'|\"([^\"\\]|\\\"|\\\'|\\)*\")"
        number="regexp:\d+"
        line_comment="regexp:#.*"
        block_comment="regexp:/\*(.|\n)*\*/"
  ]
}

mapfile ::= (MapObject | LayerObject)

//
// MAP
//
private MapObject ::= ('MAP' LayerObject* 'END')


//
// LAYER
//
private LayerObject ::= ('LAYER' ( NameAttr | TitleAttr ) 'END')


//
// SINGLE ATTRIBUTES
//
private NameAttr ::= 'NAME' notEmptyString
private TitleAttr ::= 'TITLE' notEmptyString
